# config: https://raphamorim.io/rio/docs/documentation/configuration-file
performance = "High"
theme = "tokyonight-storm"

[fonts]
size = 19
family = "FiraCode Nerd Font"

[navigation]
mode = "Plain"
