# config: https://raphamorim.io/rio/docs/documentation/configuration-file
cursor = '▇'
performance = "High"
theme = "tokyonight-storm"

# [fonts]
# family = "FiraCode Nerd Font"

[navigation]
mode = "Plain"
