# special debugger functions in TUI
[special]
# switch between tabs across all windows
switch_window_tab = ["Tab"]
# expand the left window
expand_left = ["Alt-1"]
# expand the right window
expand_right = ["Alt-2"]
# focus on the left window
focus_left = ["Ctrl-h"]
# focus on the right window
focus_right = ["Ctrl-l"]
# switch TUI to console
switch_ui = ["Esc"]
# close BugStalker
close_app = ["q"]
# continue execution
continue = ["i", "F9"]
# run or restart debugee program
run = ["e", "F10"]
# step over (next)
step_over = ["s"]
# step into (step)
step_into = ["n"]
# step out (finish)
step_out = ["r"]

# common control buttons
[common]
up = ["j"]
down = ["k"]
scroll_down = ["Ctrl-d"]
scroll_up = ["Ctrl-u"]
goto_begin = ["Home"]
goto_end = ["End"]
submit = ["Enter"]
cancel = ["Esc"]
left = ["h"]
right = ["l"]
input_delete = ["Delete"]
input_backspace = ["Backspace"]
