#!/bin/sh
paru -S --norebuild --noredownload \
	anki-bin\
	arandr\
	arch-install-scripts\
	authy\
	bitwarden\
	discord\
	evince\
	rofi\
	ttf-fira-code\
	ttf-noto-nerd\
	flameshot\
	pavucontrol\
	playerctl\
	redshift\
	signal-desktop\
	simplescreenrecorder\
	spotify\
	vimiv-qt\
	xorg\
	xclip\
	xournalpp\
	pipewire\
	pipewire-pulse\
	i3-wm\
	wireplumber\

systemctl enable --now --user wireplumber.service
systemctl enable --now --user pipewire-pulse.service
