{ self, inputs, lib, ... }:
let
  username = "tornax";
  unstable = import inputs.unstable {
    system = "x86_64-linux";
    config.allowUnfree = true;
  };

  hmModule = import ../modules/home-manager;
  sharedMainModule = import ../modules/default.nix;

  ts-ips = {
    pc = "100.64.0.1";
    nas = "100.64.0.7";
    laptop = "100.64.0.3";
    mobile = "100.64.0.4";
    server = "100.64.0.5";
  };

  ssh-keys = [
    "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIKYt8yowEzE4esfqvtHUz3xssgpe2IOGpsN/Vo5PtRD1AAAABHNzaDo="
    "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAILKD6K2md+9ItTDpBjk2sXldOZNCcKV013PExYOfoJqsAAAABHNzaDo="
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILQpLDXEFoPLUzT6a1cEh4j9OEyOpkcVQJ7jVAsQywvz Generated By Termius"
  ];

  mkSystem =
    { config-modules
    , hostname
    , ts-ip ? null
    , home-configuration ? null
    , specialArgs ? { }
    }:
    let
      hm-module =
        if home-configuration == null then
          ({ ... }: { })
        else (hmModule username home-configuration);
    in
    inputs.stable.lib.nixosSystem {
      specialArgs = lib.attrsets.recursiveUpdate specialArgs {
        inherit self inputs unstable ts-ip ts-ips ssh-keys;
      };
      modules = [
        hm-module
        (sharedMainModule hostname)
      ] ++ config-modules;
    };
in
{
  flake = {
    nixosConfigurations = {
      pc = mkSystem {
        config-modules = [ ((import ./pc) username) ];
        home-configuration = ./pc/home;
        hostname = "pc";
        ts-ip = ts-ips.pc;
      };

      laptop = mkSystem {
        config-modules = [ ((import ./laptop) username) ];
        home-configuration = ./laptop/home;
        hostname = "laptop";
        ts-ip = ts-ips.laptop;
      };

      nas = mkSystem {
        config-modules = [ ((import ./nas) username) ];
        home-configuration = ./nas/home;
        hostname = "nas";
        ts-ip = ts-ips.nas;
        specialArgs = rec {
          zpool-name = "hdds";
          zpool-root = "/${zpool-name}";

          services-root = "/services";
          root-domain = "nas.internal";
        };
      };

      server = mkSystem {
        config-modules = [ ./server ];
        hostname = "server";
        ts-ip = ts-ips.server;
        specialArgs = {
          services-root = "/services";
          root-domain = "tornaxo7.de";
          ts-root-domain = "server.internal";
          ip4 = "2.56.97.207";
          ip6 = "2a03:4000:3e:26f::";
        };
      };

      # nix build .#nixosConfigurations.iso.config.system.build.isoImage
      #
      # Just enter root automatically...
      iso = mkSystem {
        hostname = "iso";
        config-modules = [
          ({ modulesPath, ... }: {
            imports = [ (modulesPath + "/installer/cd-dvd/installation-cd-minimal.nix") ];
            config = {
              nixpkgs.hostPlatform = "x86_64-linux";
              isoImage.squashfsCompression = "lz4";

              security = {
                sudo.enable = false;
                sudo-rs.enable = true;
              };
            };
          })
        ];
      };
    };

    packages.x86_64-linux.iso = self.nixosConfigurations.iso.config.system.build.isoImage;
  };
}
