{ self, inputs, lib, ... }:
let
  username = "tornax";
  unstable = import inputs.unstable { system = "x86_64-linux"; };

  hmModule = import ../modules/home-manager;
  sharedMainModule = import ../modules/default.nix;

  ts-ips = {
    pc = "100.64.0.1";
    nas = "100.64.0.2";
    laptop = "100.64.0.3";
    mobile = "100.64.0.4";
    server = "100.64.0.5";
  };

  ssh-keys = [
    "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIKYt8yowEzE4esfqvtHUz3xssgpe2IOGpsN/Vo5PtRD1AAAABHNzaDo="
    "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAILKD6K2md+9ItTDpBjk2sXldOZNCcKV013PExYOfoJqsAAAABHNzaDo="
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILQpLDXEFoPLUzT6a1cEh4j9OEyOpkcVQJ7jVAsQywvz Generated By Termius"
  ];

  mkSystem =
    { configuration
    , hostname
    , ts-ip
    , home-configuration ? null
    , specialArgs ? { }
    }:
    let
      hm-module =
        if home-configuration == null then
          ({ ... }: { })
        else (hmModule username home-configuration);
    in
    inputs.stable.lib.nixosSystem {
      specialArgs = lib.attrsets.recursiveUpdate specialArgs {
        inherit self inputs unstable ts-ip ts-ips ssh-keys;
      };
      modules = [
        configuration
        hm-module
        (sharedMainModule hostname)
      ];
    };
in
{
  flake.nixosConfigurations = {
    pc = mkSystem {
      configuration = (import ./pc) username;
      home-configuration = ./pc/home;
      hostname = "pc";
      ts-ip = ts-ips.pc;
    };

    laptop = mkSystem {
      configuration = (import ./laptop) username;
      home-configuration = ./laptop/home;
      hostname = "laptop";
      ts-ip = ts-ips.laptop;
    };

    nas = mkSystem {
      configuration = (import ./nas) username;
      home-configuration = ./nas/home;
      hostname = "nas";
      ts-ip = ts-ips.nas;
      specialArgs = rec {
        zpool-name = "hdds";
        zpool-root = "/${zpool-name}";

        services-root = "/services";
        domain-root = "nas.local";
      };
    };

    server = mkSystem {
      configuration = ./server;
      hostname = "server";
      ts-ip = ts-ips.server;
      specialArgs = {
        services-root = "/services";
        domain-root = "tornaxo7.de";
        ip4 = "2.56.97.207";
      };
    };
  };
}
