{ self, inputs, lib, ... }:
let
  username = "tornax";
  unstable = import inputs.unstable {
    system = "x86_64-linux";
    config.allowUnfree = true;
  };

  hmModule = import ../modules/home-manager;
  sharedMainModule = import ../modules/default.nix;

  ssh-keys = [
    "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIKYt8yowEzE4esfqvtHUz3xssgpe2IOGpsN/Vo5PtRD1AAAABHNzaDo="
    "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAILKD6K2md+9ItTDpBjk2sXldOZNCcKV013PExYOfoJqsAAAABHNzaDo="
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILQpLDXEFoPLUzT6a1cEh4j9OEyOpkcVQJ7jVAsQywvz Generated By Termius"
  ];

  wg = {
    server = {
      addr = "10.0.0.1";
      publicKey = "PHvgf7n+aPJpJVxLz0g9H2JadIPCRvOeeN0azVsfXnw=";
    };
    pc = {
      addr = "10.0.0.2";
      publicKey = "h5ZTeGzZOJ2lWd6IwReNy4poNBHlG6ioaESjw0GaORc=";
    };
    nas = {
      addr = "10.0.0.3";
      publicKey = "iq//654gWYsvFKAOcYNDRmbaYlsgk46NyX4vY2qOPxM=";
    };
    laptop = {
      addr = "10.0.0.4";
      publicKey = "uv2QNQNv5qpyh21Hj3cawSWHhz1SK2VgcfECk7fnCgc=";
    };
    mobile = {
      addr = "10.0.0.5";
      publicKey = "ifkaiOHyvb99Za8kaI/MD0WV39WyvTJ4o5YCGrCv1yE=";
    };

    netmask = "10.0.0.0/24";
    domain = "tornaxo7.de";
    port = 49190;
  };

  mkSystem =
    { config-modules
    , hostname
    , home-configuration ? null
    , specialArgs ? { }
    }:
    let
      hm-module =
        if home-configuration == null then
          ({ ... }: { })
        else (hmModule username home-configuration);
    in
    inputs.stable.lib.nixosSystem {
      specialArgs = lib.attrsets.recursiveUpdate specialArgs {
        inherit self inputs unstable ssh-keys wg;
      };
      modules = [
        hm-module
        (sharedMainModule hostname)
      ] ++ config-modules;
    };
in
{
  flake = {
    nixosConfigurations = {
      pc = mkSystem {
        config-modules = [ ((import ./pc) username) ];
        home-configuration = ./pc/home;
        hostname = "pc";
      };

      laptop = mkSystem {
        config-modules = [ ((import ./laptop) username) ];
        home-configuration = ./laptop/home;
        hostname = "laptop";
      };

      nas = mkSystem {
        config-modules = [ ((import ./nas) username) ];
        home-configuration = ./nas/home;
        hostname = "nas";
        specialArgs = rec {
          zpool-name = "hdds";
          zpool-root = "/${zpool-name}";

          services-root = "/services";
          root-domain = "nas.vpn.tornaxo7.de";
        };
      };

      server = mkSystem {
        config-modules = [ ./server ];
        hostname = "server";
        specialArgs = {
          services-root = "/services";
          root-domain = wg.domain;
          ip4 = "2.56.97.207";
          ip6 = "2a03:4000:3e:26f::";
        };
      };

      # nix build .#nixosConfigurations.iso.config.system.build.isoImage
      #
      # Just enter root automatically...
      iso = mkSystem {
        hostname = "iso";
        config-modules = [
          ({ modulesPath, ... }: {
            imports = [ (modulesPath + "/installer/cd-dvd/installation-cd-minimal.nix") ];
            config = {
              nixpkgs.hostPlatform = "x86_64-linux";
              isoImage.squashfsCompression = "lz4";

              security = {
                sudo.enable = false;
                sudo-rs.enable = true;
              };
            };
          })
        ];
      };
    };

    packages.x86_64-linux.iso = self.nixosConfigurations.iso.config.system.build.isoImage;
  };
}
